# Change these first
owner: jcohoon # Your GitHub organization or username, where this repository lives
repo: vec-status # The name of this repository

sites:
  - name: VEC Claimant Self-Service
    url: https://uidirect.vec.virginia.gov/CSS/CSSLogon.htm
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: vecstatus.floretson.xyz
  # baseUrl: /jcohoon/vec-status
  logoUrl: https://raw.githubusercontent.com/jcohoon/vec-status/master/assets/img/icon.svg
  name: Virginia Employment Commission Claimant Self-Service Site Status
  introTitle: "**Service status & uptime**"
  introMessage: >
    This page shows the current and historical availability of the VEC Claimant
    Self-Service site. Automated checks run at regular intervals, and outages are
    recorded over time to provide a clear view of reliability and response
    performance.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
